"""empty message

Revision ID: a8c89d8fc374
Revises: 
Create Date: 2021-02-22 22:13:42.910014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c89d8fc374'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=90), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('password', sa.String(length=96), nullable=False),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
